### ISSUE TITLE
Torch OOM even with small chunk size

### ISSUE THREAD

**Issue by VIPQualityPost** [AlbedoFire/sd-webui-triposr#3]
I am using a 3080 and this plugin is giving me CUDA out of memory from Torch, even when using chunk_size very small (recommended from TripoSR is 8192, I tried using even down to 1024 and this still gives OOM).

**Comment by VIPQualityPost** [comment]
Also, it does not release the allocated VRAM when this happens... unlike other extensions, it will hold 10GB VRAM until I restart the server once it is tripped via triposr

**Comment by angleyanalbedo** [comment]
i have add free vram
